export class hotel{   
    key:string;
    name:string;
    district:string;
    area:string;
    address:string;
    description:string;
    hotelClass:string;
    phoneNumber:string;
    website:string; 
    emailAddress:string; 
    pool:boolean;
    roomService:boolean; 
    restuarant :boolean;
    berOrLounge :boolean;
    freeWifi :boolean;
    airportTransportation :boolean;
    breakfast :boolean;
    parking :boolean;
    wheelChairAccess :boolean;
    internetAccess :boolean;
    suits :boolean;
    aircon :boolean;
    Familyroom :boolean;
    minibar :boolean;
    Nosomke :boolean;
    smoke :boolean;
    microwave  :boolean;
    refridge :boolean;
    classic :boolean;
    mideange :boolean;
    resort :boolean;
    luxury :boolean;
    artdeco :boolean;
    parkview :boolean;
    safe :boolean;
    image1 :string;
    image2 :string;
    image3 :string;
    image4 :string;
    image5:string;
    gym:boolean;
}